### ISSUE TITLE
Hit indicator doesn't display in the correct location

### ISSUE THREAD

**Issue by npatten** [jakelawrence24/Revamped-NES-Archery#1]
It seems that regardless of where the arrow hits (and how many points you get) the straight on view of the target always displays the `X` in the bottom right. 

_note how the arrow is in the red portion of the target, but the front on view of the target shows the `X` on the blue/gray border_
<img width="914" alt="archery_bug" src="https://cloud.githubusercontent.com/assets/490006/10125286/c5003184-6533-11e5-8b9a-1feb45d8e935.png">

**Comment by npatten** [comment]
(super fun game btw!)

**Comment by lawja** [comment]
That is because you are not increasing the angle. To increase the angle hold down your click, it should appear higher then

—
